export type VocabPair = {
  hebrew: string;
  english: string;
};

export type SeedLeaf = {
  level: string;
  type: string | null;
  pairs: VocabPair[];
};

export const seedLeaves: SeedLeaf[] = [
  {
    level: "Red",
    type: null,
    pairs: [
      { hebrew: "שָׁלוֹם", english: "Hello / Peace" },
      { hebrew: "תּוֹדָה", english: "Thank you" },
      { hebrew: "בְּבַקָּשָׁה", english: "Please / You're welcome" },
      { hebrew: "כֵּן", english: "Yes" },
      { hebrew: "לֹא", english: "No" },
      { hebrew: "מַיִם", english: "Water" },
      { hebrew: "קָפֶה", english: "Coffee" },
      { hebrew: "שֵׁם", english: "Name" },
      { hebrew: "מָה", english: "What" },
      { hebrew: "אֵיךְ", english: "How" },
    ],
  },
  {
    level: "Orange",
    type: null,
    pairs: [
      { hebrew: "אֲנִי", english: "I" },
      { hebrew: "אַתָּה", english: "You (m.s.)" },
      { hebrew: "אַתְּ", english: "You (f.s.)" },
      { hebrew: "הוּא", english: "He" },
      { hebrew: "הִיא", english: "She" },
      { hebrew: "אוֹהֵב", english: "Love / Like (m.)" },
      { hebrew: "רוֹצֶה", english: "Want (m.)" },
      { hebrew: "יָכוֹל", english: "Can / Able (m.)" },
      { hebrew: "הַיּוֹם", english: "Today" },
      { hebrew: "מָחָר", english: "Tomorrow" },
    ],
  },
  {
    level: "Pink",
    type: null,
    pairs: [
      { hebrew: "הָלַכְתִּי", english: "I went" },
      { hebrew: "אָכַלְתִּי", english: "I ate" },
      { hebrew: "רָאִיתִי", english: "I saw" },
      { hebrew: "דִּבַּרְתִּי", english: "I spoke" },
      { hebrew: "עָשִׂיתִי", english: "I did / made" },
      { hebrew: "אֶתְמוֹל", english: "Yesterday" },
      { hebrew: "שָׁבוּעַ", english: "Week" },
      { hebrew: "חֹדֶשׁ", english: "Month" },
      { hebrew: "מִשְׁפָּחָה", english: "Family" },
      { hebrew: "חָבֵר", english: "Friend (m.)" },
    ],
  },
  {
    level: "Yellow",
    type: null,
    pairs: [
      { hebrew: "אֵלֵךְ", english: "I will go" },
      { hebrew: "אֹכַל", english: "I will eat" },
      { hebrew: "אֶרְאֶה", english: "I will see" },
      { hebrew: "אֲדַבֵּר", english: "I will speak" },
      { hebrew: "אַעֲשֶׂה", english: "I will do / make" },
      { hebrew: "בַּעֲתִיד", english: "In the future" },
      { hebrew: "תָּכְנִית", english: "Plan" },
      { hebrew: "נְסִיעָה", english: "Trip / Ride" },
      { hebrew: "עֲבוֹדָה", english: "Work / Job" },
      { hebrew: "לִלְמֹד", english: "To learn / study" },
    ],
  },

  {
    level: "Light Blue",
    type: null,
    pairs: [
      { hebrew: "הִתְחַלְתִּי", english: "I started" },
      { hebrew: "הִצְטַעַרְתִּי", english: "I was sorry" },
      { hebrew: "נִפְגַּשְׁנוּ", english: "We met" },
      { hebrew: "הִרְגַּשְׁתִּי", english: "I felt" },
      { hebrew: "הִסְתַּכַּלְתִּי", english: "I looked" },
      { hebrew: "בְּעָיָה", english: "Problem" },
      { hebrew: "פִּתְרוֹן", english: "Solution" },
      { hebrew: "נִסָּיוֹן", english: "Experience / Attempt" },
      { hebrew: "הַחלָטָה", english: "Decision" },
      { hebrew: "הַזְמָנָה", english: "Invitation / Order" },
    ],
  },
  {
    level: "Blue",
    type: null,
    pairs: [
      { hebrew: "אֶתְעוֹרֵר", english: "I will wake up" },
      { hebrew: "אֶתְלַבֵּשׁ", english: "I will get dressed" },
      { hebrew: "נִתְרָאֶה", english: "See you / We'll see each other" },
      { hebrew: "מִסְתַּדֵּר", english: "Working out / Managing" },
      { hebrew: "מִתְעַנְיֵן", english: "Interested (m.)" },
      { hebrew: "אַחְרָיוּת", english: "Responsibility" },
      { hebrew: "הַזְדַּמְּנוּת", english: "Opportunity" },
      { hebrew: "יַחַס", english: "Attitude / Relationship" },
      { hebrew: "תְּחוּשָׁה", english: "Feeling / Sensation" },
      { hebrew: "צִיפִּיָּה", english: "Expectation" },
    ],
  },
  {
    level: "Lime",
    type: null,
    pairs: [
      { hebrew: "גַּם אִם", english: "Even if" },
      { hebrew: "לְמָרוֹת", english: "Despite" },
      { hebrew: "בִּגְלַל", english: "Because of" },
      { hebrew: "כְּדֵי שֶׁ", english: "So that" },
      { hebrew: "אַף עַל פִּי", english: "Even though" },
      { hebrew: "הַשְׁפָּעָה", english: "Influence / Impact" },
      { hebrew: "הֶקְשֵׁר", english: "Context" },
      { hebrew: "גִּישָׁה", english: "Approach" },
      { hebrew: "מַסְקָנָה", english: "Conclusion" },
      { hebrew: "דֻּגְמָה", english: "Example" },
    ],
  },
  {
    level: "Green",
    type: null,
    pairs: [
      { hebrew: "מֻרְכָּב", english: "Complex / Complicated" },
      { hebrew: "פָּשׁוּט", english: "Simple" },
      { hebrew: "מְדֻיָּק", english: "Accurate / Precise" },
      { hebrew: "גָּמִישׁ", english: "Flexible" },
      { hebrew: "יַצִּיב", english: "Stable" },
      { hebrew: "תִּקְשֹּרֶת", english: "Communication" },
      { hebrew: "שִׁתּוּף פְּעֻלָּה", english: "Cooperation" },
      { hebrew: "יְעִילוּת", english: "Efficiency" },
      { hebrew: "אִתְגָּר", english: "Challenge" },
      { hebrew: "הִתְפַּתְּחוּת", english: "Development" },
    ],
  },

  {
    level: "Dark Green",
    type: "Pack 1",
    pairs: [
      { hebrew: "שִׂיחָה", english: "Conversation / Discussion" },
      { hebrew: "וִכּוּחַ", english: "Debate" },
      { hebrew: "טַעֲנָה", english: "Claim / Argument" },
      { hebrew: "נִמּוּק", english: "Reasoning / Justification" },
      { hebrew: "הַסְכָּמָה", english: "Agreement" },
      { hebrew: "חִלּוּקֵי דֵּעוֹת", english: "Disagreement" },
      { hebrew: "נְקֻדַּת מַבָּט", english: "Point of view" },
      { hebrew: "שִׁכְנוּעַ", english: "Persuasion" },
      { hebrew: "בִּקֹּרֶת", english: "Criticism / Review" },
      { hebrew: "תְּגוּבָה", english: "Response / Reaction" },
    ],
  },
  {
    level: "Dark Green",
    type: "Pack 2",
    pairs: [
      { hebrew: "מְהַדּוּרָה", english: "Edition / Broadcast" },
      { hebrew: "כַּתָּבָה", english: "Article / Report" },
      { hebrew: "רְאָיוֹן", english: "Interview" },
      { hebrew: "כּוֹתֶרֶת", english: "Headline" },
      { hebrew: "מְקוֹר", english: "Source" },
      { hebrew: "סִקּוּר", english: "Coverage" },
      { hebrew: "שִׁדּוּר", english: "Broadcast" },
      { hebrew: "צִנְזוּרָה", english: "Censorship" },
      { hebrew: "דֵּעָה קְהַלִּית", english: "Public opinion" },
      { hebrew: "מֶיְדָע", english: "Information" },
    ],
  },
  {
    level: "Dark Green",
    type: "Pack 3",
    pairs: [
      { hebrew: "בִּטָּחוֹן", english: "Security / Confidence" },
      { hebrew: "מְדִינִיּוּת", english: "Policy / Politics" },
      { hebrew: "חֶבְרָה", english: "Society / Company" },
      { hebrew: "כַּלְכָּלָה", english: "Economy" },
      { hebrew: "תַּרְבּוּת", english: "Culture" },
      { hebrew: "זְכוּיוֹת", english: "Rights" },
      { hebrew: "חוֹבָה", english: "Duty / Obligation" },
      { hebrew: "שִׁוְיוֹן", english: "Equality" },
      { hebrew: "צֶדֶק", english: "Justice" },
      { hebrew: "חֵרוּת", english: "Freedom / Liberty" },
    ],
  },
  {
    level: "Dark Green",
    type: "Pack 4",
    pairs: [
      { hebrew: "לְהִתְבַּטֵּא", english: "To express oneself" },
      { hebrew: "לְנַסֵּחַ", english: "To formulate / phrase" },
      { hebrew: "לְהַדְגִּישׁ", english: "To emphasize" },
      { hebrew: "לְהַבְחִין", english: "To distinguish / notice" },
      { hebrew: "לְהַסְבִּיר", english: "To explain" },
      { hebrew: "לְסַכֵּם", english: "To summarize" },
      { hebrew: "לְהַשְׁווֹת", english: "To compare" },
      { hebrew: "לְהַפְרִיךְ", english: "To refute" },
      { hebrew: "לְתַמֵּךְ", english: "To support" },
      { hebrew: "לְהִתְנַגֵּד", english: "To oppose" },
    ],
  },

  {
    level: "Turquoise",
    type: "Pack 1",
    pairs: [
      { hebrew: "שְׁטִיפָה", english: "Fluency (of speech)" },
      { hebrew: "בִּטָּחוֹן עַצְמִי", english: "Self-confidence" },
      { hebrew: "הִתְבַּטְּאוּת", english: "Expression / Utterance" },
      { hebrew: "נִימוּס", english: "Courtesy / Manners" },
      { hebrew: "סְגָנוֹן", english: "Style" },
      { hebrew: "נִיב", english: "Idiom / Dialect" },
      { hebrew: "מְלִיצָה", english: "Figurative speech" },
      { hebrew: "קֶצֶב", english: "Pace / Rhythm" },
      { hebrew: "הֲגִיָּה", english: "Pronunciation" },
      { hebrew: "הַטְעָמָה", english: "Stress / Intonation" },
    ],
  },
  {
    level: "Turquoise",
    type: "Pack 2",
    pairs: [
      { hebrew: "תַּחְבִּיר", english: "Syntax" },
      { hebrew: "מוֹרְפוֹלוֹגְיָה", english: "Morphology" },
      { hebrew: "שֹׁרֶשׁ", english: "Root (of a word)" },
      { hebrew: "בִּנְיָן", english: "Verb pattern (binyan)" },
      { hebrew: "נְטִיָּה", english: "Inflection / Conjugation" },
      { hebrew: "מִלַּת יַחַס", english: "Preposition" },
      { hebrew: "כִּנּוּי", english: "Pronoun / Nickname" },
      { hebrew: "תֹּאַר", english: "Adjective / Title" },
      { hebrew: "פֹּעַל", english: "Verb" },
      { hebrew: "שֵׁם עֶצֶם", english: "Noun" },
    ],
  },
  {
    level: "Turquoise",
    type: "Pack 3",
    pairs: [
      { hebrew: "צְפִיָּה", english: "Watching / Anticipation" },
      { hebrew: "סִדְרָה", english: "Series (TV)" },
      { hebrew: "תַּסְרִיט", english: "Script / Screenplay" },
      { hebrew: "עִלּוּם", english: "Filming / Concealment" },
      { hebrew: "דְּמוּת", english: "Character / Figure" },
      { hebrew: "עֲלִילָה", english: "Plot" },
      { hebrew: "מַשְׁמָעוּת", english: "Meaning / Significance" },
      { hebrew: "רֶמֶז", english: "Hint / Allusion" },
      { hebrew: "סַטִירָה", english: "Satire" },
      { hebrew: "הוּמוֹר", english: "Humor" },
    ],
  },
  {
    level: "Turquoise",
    type: "Pack 4",
    pairs: [
      { hebrew: "קְרִיאָה מֻרְחֶבֶת", english: "Extensive reading" },
      { hebrew: "קֶצֶב קְרִיאָה", english: "Reading speed" },
      { hebrew: "הֲבָנָה", english: "Comprehension" },
      { hebrew: "פִּסְקָה", english: "Paragraph" },
      { hebrew: "פֶּרֶק", english: "Chapter" },
      { hebrew: "תַּקְצִיר", english: "Abstract / Summary" },
      { hebrew: "הֶעָרָה", english: "Note / Remark" },
      { hebrew: "מָבוֹא", english: "Introduction" },
      { hebrew: "סִיּוּם", english: "Ending / Conclusion" },
      { hebrew: "מַפְתֵּחַ", english: "Key / Index" },
    ],
  },

  {
    level: "Indigo",
    type: "Pack 1",
    pairs: [
      { hebrew: "מִלּוֹן", english: "Dictionary / Vocabulary" },
      { hebrew: "מִלָּה נִרְדֶּפֶת", english: "Synonym" },
      { hebrew: "נִגּוּד", english: "Antonym / Contrast" },
      { hebrew: "מֶטָפוֹרָה", english: "Metaphor" },
      { hebrew: "דִּמּוּי", english: "Simile / Image" },
      { hebrew: "בִּטּוּי", english: "Expression / Phrase" },
      { hebrew: "פִּתְגָּם", english: "Proverb" },
      { hebrew: "סְלֶנְג", english: "Slang" },
      { hebrew: "לָשׁוֹן גְּבוֹהָה", english: "Elevated / Formal language" },
      { hebrew: "לָשׁוֹן דִּבּוּר", english: "Colloquial speech" },
    ],
  },
  {
    level: "Indigo",
    type: "Pack 2",
    pairs: [
      { hebrew: "אִינְטוּאִיצְיָה", english: "Intuition" },
      { hebrew: "תְּחוּשַׁת בֶּטֶן", english: "Gut feeling" },
      { hebrew: "שִׁקּוּל דַּעַת", english: "Judgment / Discretion" },
      { hebrew: "הִגָּיוֹן", english: "Logic" },
      { hebrew: "הִסֵּק", english: "Inference" },
      { hebrew: "הַנָּחָה", english: "Assumption" },
      { hebrew: "סְבָרָה", english: "Conjecture / Opinion" },
      { hebrew: "וַדָּאוּת", english: "Certainty" },
      { hebrew: "סָפֵק", english: "Doubt" },
      { hebrew: "אֲמִתּוּת", english: "Truthfulness / Validity" },
    ],
  },
  {
    level: "Indigo",
    type: "Pack 3",
    pairs: [
      { hebrew: "פֹּרְמָלִי", english: "Formal" },
      { hebrew: "בִּלְתִּי פֹּרְמָלִי", english: "Informal" },
      { hebrew: "רִשְׁמִי", english: "Official" },
      { hebrew: "יְדִידוּתִי", english: "Friendly / Informal" },
      { hebrew: "מְכֻבָּד", english: "Respectful / Honored" },
      { hebrew: "יָשִׁיר", english: "Direct / Straightforward" },
      { hebrew: "עֲקִיף", english: "Indirect" },
      { hebrew: "עֲדִין", english: "Delicate / Gentle" },
      { hebrew: "נָחְשָׁנִי", english: "Assertive" },
      { hebrew: "דִּפְּלוֹמָטִי", english: "Diplomatic" },
    ],
  },
  {
    level: "Indigo",
    type: "Pack 4",
    pairs: [
      { hebrew: "חֹרֶג", english: "Irregular / Exceptional" },
      { hebrew: "חֲרִיגָה", english: "Exception / Deviation" },
      { hebrew: "כְּלָל", english: "Rule" },
      { hebrew: "יוֹצֵא מִן הַכְּלָל", english: "Exception to the rule" },
      { hebrew: "דֻּגְמַת נֶגֶד", english: "Counterexample" },
      { hebrew: "תִּקּוּן", english: "Correction / Repair" },
      { hebrew: "שִׁנּוּי", english: "Change" },
      { hebrew: "הִתְאָמָה", english: "Adaptation / Fit" },
      { hebrew: "הַטָּיָה", english: "Bias / Inclination" },
      { hebrew: "סְטִיָּה", english: "Deviation" },
    ],
  },
  {
    level: "Indigo",
    type: "Pack 5",
    pairs: [
      { hebrew: "נִיּוּאַנְס", english: "Nuance" },
      { hebrew: "דֹּק", english: "Subtlety / Fineness" },
      { hebrew: "רֶמֶז דַּק", english: "Subtle hint" },
      { hebrew: "כַּוָּנָה", english: "Intention / Meaning" },
      { hebrew: "מַשְׁמָעוּת כְּפוּלָה", english: "Double meaning" },
      { hebrew: "אִירוֹנְיָה", english: "Irony" },
      { hebrew: "סַרְקַזְם", english: "Sarcasm" },
      { hebrew: "חִדּוּד", english: "Wit / Sharpening" },
      { hebrew: "עֲמִימוּת", english: "Ambiguity" },
      { hebrew: "בְּהִירוּת", english: "Clarity" },
    ],
  },
  {
    level: "Indigo",
    type: "Pack 6",
    pairs: [
      { hebrew: "לְהִשְׁתַּמֵּשׁ בְּאֹפֶן טִבְעִי", english: "To use naturally" },
      { hebrew: "לְהִתְנַסּוֹת", english: "To experience / try out" },
      { hebrew: "לְהַפְנִים", english: "To internalize" },
      { hebrew: "לְשַׁפְרֵץ", english: "To improve (colloq.)" },
      { hebrew: "לְחַדֵּד", english: "To sharpen / refine" },
      { hebrew: "לְהַעֲמִיק", english: "To deepen" },
      { hebrew: "לְהַרְחִיב", english: "To expand" },
      { hebrew: "לְיַשֵּׁם", english: "To apply / implement" },
      { hebrew: "לְהִסְתַּגֵּל", english: "To adapt" },
      { hebrew: "לְשַׁלֵּב", english: "To integrate / combine" },
    ],
  },

  {
    level: "Purple",
    type: null,
    pairs: [
      { hebrew: "מִלּוּי פְּעָרִים", english: "Filling gaps" },
      { hebrew: "דִּיּוּן", english: "Discussion / Debate" },
      { hebrew: "טִיעוּן", english: "Argumentation" },
      { hebrew: "נִיתוּחַ", english: "Analysis" },
      { hebrew: "סִנְתֵּז", english: "Synthesis" },
      { hebrew: "הַעֲרָכָה", english: "Evaluation / Appreciation" },
      { hebrew: "פֵּרוּשׁ", english: "Interpretation / Commentary" },
      { hebrew: "הַקְשָׁרָה", english: "Contextualization" },
      { hebrew: "רְאִיָּה רְחָבָה", english: "Broad perspective" },
      { hebrew: "שְׁלֵמוּת", english: "Completeness / Wholeness" },
    ],
  },
];
